'use strict';
const assert = require('node:assert/strict');
const { Simulator, domain, answer } = require('./engine');
const facts = domain();
assert.equal(facts.length, 132);
assert.equal(new Set(facts.map(f => `${f.a}${f.op}${f.b}`)).size, 132);
assert.equal(facts.filter(f => f.op === '+').length, 66);
assert(facts.every(f => f.a >= 0 && f.b >= 0 && answer(f) >= 0 && answer(f) <= 10));
const runA = new Simulator({ steps: 300 }).run();
const runB = new Simulator({ steps: 300 }).run();
assert.deepEqual(runA.export(), runB.export(), 'Same seed must reproduce the entire run');
const differentLearner = new Simulator({ steps: 300, forgetting: .9, comparison: 0, learning: .8, lessons: [] }).run();
assert.deepEqual(runA.history.map(({a,b,op}) => [a,b,op]), differentLearner.history.map(({a,b,op}) => [a,b,op]), 'Learner settings must not change exercise order');
const before = JSON.stringify(runA.export());
runA.assess(); runA.assess();
assert.equal(JSON.stringify(runA.export()), before, 'Assessment must not mutate learner state');
assert.deepEqual(runA.next(), runB.next(), 'Assessment must not consume practice randomness');
for (const order of ['mixed', 'alternating', 'families', 'blocked', 'small', 'deliberate']) {
  const sim = new Simulator({ steps: 250, order, slip: 0, lessons: [] }).run();
  assert(sim.history.every(r => r.correct), `${order}: no errors without execution slips`);
  assert(sim.history.some(r => r.op === '+') && sim.history.some(r => r.op === '-'));
  assert(sim.history.every(r => r.totalCost >= r.cost && r.cost >= 0));
}
const baseline = new Simulator({ slip: 0, learning: 0, comparison: 0, exploration: 0, forgetting: 0, lessons: [] });
assert.equal(baseline.next({ a: 3, b: 4, op: '+' }).cost, 14);
assert.equal(baseline.next({ a: 7, b: 3, op: '-' }).cost, 17);
assert.equal(baseline.next({ a: 0, b: 0, op: '+' }).cost, 0);
const taught = new Simulator({ slip: 0, learning: 0, exploration: 0, comparison: 0, lessons: [{ step: 2, rule: 'countOn' }] });
assert.equal(taught.next({ a: 3, b: 4, op: '+' }).strategy, 'draw');
const short = taught.next({ a: 3, b: 4, op: '+' });
assert.equal(short.strategy, 'count'); assert.equal(short.cost, 5); assert.equal(taught.events[0].step, 2);
const implicit = new Simulator({ comparison: 1, learning: 1, slip: 0, exploration: 0, forgetting: 0, lessons: [] });
for (const [a, b] of [[1,2],[2,1],[1,3],[3,1],[2,3],[3,2]]) implicit.next({ a,b,op:'+' });
assert.equal(implicit.rules.commutative.origin, 'implicit');
assert.equal(implicit.rules.commutative.evidence.length, 3);
assert.equal(implicit.rules.countOn.origin, null, 'Counting-on is a taught procedure in v1');
const noCompare = new Simulator({ comparison: 0, lessons: [] }).run(800);
assert(Object.values(noCompare.rules).every(r => !r.origin), 'No implicit induction without comparison');
assert(noCompare.history.every(r => !r.comparison.attempted && r.learningCost === 0));
for (const model of ['associative', 'actr', 'neural']) {
  const config = { model, comparison: 1, learning: 0, slip: 0, exploration: 0, forgetting: 0, lessons: [] };
  const distant = new Simulator(config);
  for (const [a,b] of [[1,2],[4,4],[2,1],[1,3],[4,4],[3,1],[2,3],[4,4],[3,2]]) distant.next({a,b,op:'+'});
  assert.equal(distant.rules.commutative.evidence.length, 0, `${model}: no discovery from nonconsecutive facts`);
  const adjacent = new Simulator(config);
  for (const [a,b] of [[1,2],[2,1],[1,3],[3,1],[2,3],[3,2]]) adjacent.next({a,b,op:'+'});
  assert.equal(adjacent.rules.commutative.learnedAt, 6);
  assert.deepEqual(adjacent.history.at(-1).comparison.acquired, ['commutative']);
  assert(adjacent.history.every((r,i) => r.comparison.previousStep === (i || null)));
  assert.equal(adjacent.history[0].learningCost, 0);
  assert(adjacent.history.slice(1).every(r => r.learningCost === 1), 'Every attempted comparison costs effort, even without a match');
  adjacent.next({a:1,b:2,op:'+'}); adjacent.next({a:2,b:1,op:'+'});
  assert.equal(adjacent.rules.commutative.evidence.length, 3, 'Repeating a pair does not create distinct evidence');
}
const pairRules = new Simulator({ comparison:1, slip:0, forgetting:0, lessons:[] });
pairRules.next({a:1,b:0,op:'+'});
assert.equal(pairRules.rules.zero.evidence.length, 0, 'One exercise alone cannot establish a comparison pattern');
pairRules.next({a:2,b:0,op:'+'});
assert.equal(pairRules.rules.zero.evidence.length, 1);
pairRules.next({a:3,b:3,op:'-'}); pairRules.next({a:4,b:4,op:'-'});
assert.equal(pairRules.rules.self.evidence.length, 1);
pairRules.next({a:2,b:3,op:'+'}); pairRules.next({a:2,b:4,op:'+'});
assert.equal(pairRules.rules.neighbor.evidence.length, 1);
pairRules.next({a:6,b:4,op:'-'});
assert.equal(pairRules.rules.inverse.evidence.length, 1);
const gate = new Simulator({comparison:.4, slip:0, lessons:[]});
gate.next({a:1,b:2,op:'+'}); gate.step++;
gate.remember({a:2,b:1,op:'+'},3);
gate.random = () => .4;
assert.equal(gate.discover({a:2,b:1,op:'+'}).attempted, false, 'Index is the comparison probability');
gate.random = () => .39;
assert.deepEqual(gate.discover({a:2,b:1,op:'+'}).evidenceAdded, ['commutative']);
const wrongPair = new Simulator({comparison:1, feedback:'none', slip:0, lessons:[]});
wrongPair.next({a:2,b:3,op:'+'}); wrongPair.step++;
wrongPair.remember({a:3,b:2,op:'+'},7);
assert.deepEqual(wrongPair.discover({a:3,b:2,op:'+'}).evidenceAdded, [], 'Compare observed answers, not correct-answer oracle');
const fixed = new Simulator({ comparison: 0, forgetting: 0, learning: .5, slip: 0, exploration: 0, lessons: [] });
for (let i = 0; i < 5; i++) fixed.next({ a: 3, b: 4, op: '+' });
assert.equal(fixed.history.at(-1).strategy, 'recall');
const forgetful = new Simulator({ forgetting: 1, lessons: [], comparison: 0 });
forgetful.memory.set('3+4', { fact: { a:3, b:4, op:'+' }, value:7, strength:1, lastSeen:0 });
for (let i = 0; i < 1000; i++) forgetful.decay();
assert(forgetful.memory.get('3+4').strength < .2, 'Unrehearsed facts must weaken');
const noFeedback = new Simulator({ feedback: 'none', learning: 1, comparison: 1, slip: 0, lessons: [] });
noFeedback.remember({ a: 2, b: 0, op: '+' }, 7);
noFeedback.discover({ a: 2, b: 0, op: '+' });
assert.equal(noFeedback.rules.zero.evidence.length, 0, 'Rule evidence must use observed answers, not oracle answers');
const total = runB.history.reduce((s,r) => s+r.cost,0);
assert(Number.isFinite(total));
const factKey = f => `${f.a}${f.op}${f.b}`;
const deliberate = new Simulator({ order: 'deliberate', forgetting: 0, slip: 0, lessons: [] });
facts.forEach((fact, i) => deliberate.memory.set(factKey(fact), { fact, value: answer(fact), strength: i < 27 ? .1 : .9, lastSeen: 0 }));
const weakestKeys = new Set(facts.slice(0, 27).map(factKey));
const selected = new Set(Array.from({ length: 200 }, () => factKey(deliberate.chooseExercise())));
assert([...selected].every(k => weakestKeys.has(k)), 'Only the weakest fifth should be selected');
assert(selected.size > 1, 'Selection among weak facts must vary');
// All strengths tied: selection must not be confined to the first 27 facts.
deliberate.memory.clear();
const tied = new Set(Array.from({ length: 200 }, () => factKey(deliberate.chooseExercise())));
assert(tied.size > 27, 'Include all ties, including unseen facts');
facts.forEach((fact, i) => deliberate.memory.set(factKey(fact), { fact, value: answer(fact), strength: i / 200, lastSeen: 0 }));
const wrongFact = facts.at(-1);
deliberate.memory.set(factKey(wrongFact), { fact: wrongFact, value: -1, strength: 1, lastSeen: 0 });
const withWrong = new Set(Array.from({ length: 300 }, () => factKey(deliberate.chooseExercise())));
assert(withWrong.has(factKey(wrongFact)), 'Confident wrong answers must be eligible as weakest');
assert(!withWrong.has(factKey(facts.at(-2))), 'Strong correct answers must be excluded');
const adaptiveConfig = { order: 'deliberate', steps: 200, seed: 99 };
assert.deepEqual(new Simulator(adaptiveConfig).run().export(), new Simulator(adaptiveConfig).run().export(), 'Adaptive runs must reproduce with the same seed and settings');
console.log('Passed: domain, deterministic runs, non-training diagnostics, six practice schedules, action costs, lessons, implicit evidence, recall, and deliberate-practice ranking/ties.');
